### PR TITLE
Add idle sorting

### PR DESCRIPTION
**Pull request by AeroNotix**

### CODE REVIEW

**Comment by bchretien** [comment]
Thanks! Can you recommit this without all the removed trailing whitespaces? That way it's easier to keep track of exactly what changed. To help you, use `git add -p` to select relevant lines before commiting.

**Comment by AeroNotix** [comment]
Sure

**Comment by AeroNotix** [comment]
@bchretien done

**Comment by bchretien** [comment]
LGTM :+1: Thanks!

**Comment by AeroNotix** [comment]
Cheers

**Pull request merged**
